steps:
  - name: bash
    id: create env
    script: |
      #!/usr/bin/env bash
      printenv > .env
    dir: "server"
    env:
      - NODE_PORT=${_NODE_PORT}
      - TZ=${_TZ}

      - DB_DATABASE=${_DB_DATABASE}
      - DB_USER_NAME=${_DB_USER_NAME}
      - DB_PASSWORD=${_DB_PASSWORD}
      - DB_HOST=${_DB_HOST}
      - DB_DIALECT=${_DB_DIALECT}

      - JWT_KEY_STAFF_MEMBERS=${_JWT_KEY_STAFF_MEMBERS}
      - JWT_KEY_USER=${_JWT_KEY_USER}

      - SMS_ACCOUNT_SID=${_SMS_ACCOUNT_SID}
      - SMS_AUTH_TOKEN=${_SMS_AUTH_TOKEN}
      - SMS_SENDER_NAME=${_SMS_SENDER_NAME}

      - EMAIL_CLIENT_ID=${_EMAIL_CLIENT_ID}
      - EMAIL_CLIENT_SECRET=${_EMAIL_CLIENT_SECRET}
      - EMAIL_REDIRECT_URI=${_EMAIL_REDIRECT_URI}
      - EMAIL_ACCESS_TOKEN=${_EMAIL_ACCESS_TOKEN}
      - EMAIL_REFRESH_TOKEN=${_EMAIL_REFRESH_TOKEN}
      - EMAIL_FROM=${_EMAIL_FROM}

      - BASIC_URL=${_BASIC_URL}

  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
    dir: "server"
timeout: "1600s"
