steps:
  - name: node:20.10.0
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - NODE_PORT=${_NODE_PORT}
      - TZ=${_TZ}

      - DB_DATABASE=${_DB_DATABASE}
      - DB_USER_NAME=${_DB_USER_NAME}
      - DB_PASSWORD=${_DB_PASSWORD}
      - DB_HOST=${_DB_HOST}
      - DB_DIALECT=${_DB_DIALECT}

      - OLD_DB_DATABASE=${_OLD_DB_DATABASE}
      - OLD_DB_USER_NAME=${_OLD_DB_USER_NAME}
      - OLD_DB_PASSWORD=${_OLD_DB_PASSWORD}
      - OLD_DB_HOST=${_OLD_DB_HOST}
      - OLD_DB_DIALECT=${_OLD_DB_DIALECT}

      - JWT_KEY_STAFF_MEMBERS=${_JWT_KEY_STAFF_MEMBERS}
      - JWT_KEY_USER=${_JWT_KEY_USER}

      - SMS_ACCOUNT_SID=${_SMS_ACCOUNT_SID}
      - SMS_AUTH_TOKEN=${_SMS_AUTH_TOKEN}
      - SMS_SENDER_NAME=${_SMS_SENDER_NAME}

      - BASIC_URL=${_BASIC_URL}

      - NAMER_URL=${_NAMER_URL}
      - NAMER_USERNAME=${_NAMER_USERNAME}
      - NAMER_PASSWORD=${_NAMER_PASSWORD}
      - NAMER_USER_ID=${_NAMER_USER_ID}

    dir: "server"
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
    dir: "server"
timeout: "1600s"
